# Generated by Django 5.0.6 on 2024-05-28 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_addjob_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob_model',
            name='job_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
