# Generated by Django 5.0.6 on 2024-06-08 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_Aplly_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=120, null=True)),
                ('salary', models.CharField(max_length=120, null=True)),
                ('apply_resume', models.FileField(max_length=120, null=True, upload_to='')),
                ('aplicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.addjob_model')),
            ],
        ),
    ]
