# Generated by Django 5.0.6 on 2024-06-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_job_aplly_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_Aplly_model',
            new_name='job_Apply_model',
        ),
    ]
